export interface Feedback {
  quote: string
  name: string
  college: string | null
  location: string | null
}

export const colleges = [
  "M.A. Rangoonwala College of Physiotherapy and Research",
  "Reva University",
  "Indutai Gaikwad Patil College of Physiotherapy",
  "Dolphin PG College, Dehradun",
  "Tagore College of Physiotherapy",
  "Sree Balaji College of Physiotherapy",
  "SIMS College of Physiotherapy",
  "JP Group of Institutions",
  "KPGU",
  "Susruta Institute of Physical Medicine and Rehabilitation",
  "Mahalaxmi College of Physiotherapy",
  "SAAII College of Medical Science and Technology",
  "SGRD",
  "Shree M.M. Shah Physiotherapy College",
]

export const feedbacks: Feedback[] = [
  {
    quote: "It was really informative",
    name: "Arunshek",
    college: null,
    location: "Tamil",
  },
  {
    quote: "Fastly coverd by this session",
    name: "Abhishek kr",
    college: null,
    location: "Bihar",
  },
  {
    quote: "it was really wonderful such a nice mantor thank you so much for that informative session",
    name: "nawab said",
    college: null,
    location: "sindh",
  },
  {
    quote: "Just wonderful session. Most of the things are cleared",
    name: "Megha",
    college: null,
    location: "Uttar Pradesh",
  },
  {
    quote: "This was the first time I attended a session like this and the experience was great. Success of the sessions or seminars depends upon the host and for me the session was definitely a success and I'm definitely looking forward for more such amazing session.",
    name: "Anjali",
    college: null,
    location: "Haryana",
  },
  {
    quote: "This is very wonderful session",
    name: "Saili Gharkar",
    college: null,
    location: "Maharashtra",
  },
  {
    quote: "Osm",
    name: "MD. MARGHOOB NEYAZI",
    college: null,
    location: "Rajasthan",
  },
  {
    quote: "Explain in easy language",
    name: "ARATI Vijay Jadhav",
    college: null,
    location: "Maharashtra",
  },
  {
    quote: "Good 👍",
    name: "Ratnam",
    college: null,
    location: "Karnataka",
  },
  {
    quote: "Nice session",
    name: "Purab Sinha",
    college: null,
    location: "Bihar",
  },
  {
    quote: "Best productive session",
    name: "Dr Touqeer Abbas",
    college: null,
    location: "Punjab",
  },
  {
    quote: "Very nice explanation",
    name: "Dr Shifa Shaikh",
    college: null,
    location: "Ahmedabad",
  },
  {
    quote: "It has been very wonderful. I have been waiting for it for a very long time",
    name: "Rachkara Samuel Baker",
    college: null,
    location: "Central Uganda",
  },
  {
    quote: "Very well explained sir..",
    name: "Shivam Mishra",
    college: null,
    location: "UP",
  },
  {
    quote: "It was good",
    name: "M anil kumar",
    college: null,
    location: "Telangana",
  },
  {
    quote: "Lec is good but treatment portion is very less ..",
    name: "Aryan Patel",
    college: null,
    location: "Gujarat",
  },
  {
    quote: "The Sedative Physio webinar on shoulder instability and its rehab was really helpful! The session was clear, easy to understand, and packed with useful information. I learned a lot about shoulder instability and how to approach its rehab effectively. I definitely recommend this webinar to anyone wanting to improve their physiotherapy skills!",
    name: "Abhishek Singh",
    college: null,
    location: "Delhi",
  },
  {
    quote: "It was a wonderful session. Sir explained each and every topic of Shoulder Instability in detailed. Specially the rehab program was also very precise. Hope to attend more such sessions in future.",
    name: "Namita",
    college: null,
    location: "West Bengal",
  },
  {
    quote: "The webinar on Shoulder Instability was concise, informative, and engaging. The speaker explained complex concepts clearly, covering anatomy, diagnosis, and management effectively. The Q&A session and evidence-based insights were particularly valuable. Thank you for an excellent learning experience!",
    name: "Ashutosh",
    college: null,
    location: "Karnataka",
  },
  {
    quote: "This webinar provided clear and concise insights into shoulder instability. The content was practical and evidence-based, making it both engaging and highly relevant. Thank you for a fantastic session!",
    name: "Smith",
    college: null,
    location: "London",
  },
  {
    quote: "Great session had a lot of information",
    name: "Mirza",
    college: "M.A RANGOONWALA COLLEGE OF PHYSIOTHERAPY AND RESEARCH",
    location: null,
  },
  {
    quote: "Nice webinar",
    name: "Husam Maged",
    college: "Reva University",
    location: null,
  },
  {
    quote: "I loved the session.It was worth every penny. Best thing was that sir repeatedly explained the topic whenever we asked him. I really enjoyed the session,it wasn't boring at all. The only thing I want to mention is the speed...it will be very helpful and easy to understand if sir explains at slow pace...Rest everything was awesome",
    name: "Mrunalini Sorgile",
    college: "Indutai Gaikwad Patil College of Physiotherapy",
    location: null,
  },
  {
    quote: "Today I learn lots of new knowledge on parkinson Webinar very effective full and very useful for knowledge Thank you so much Dr Rohit sen Consultant physiotherapy At Fortis escorts heart' institute okhla delhi",
    name: "Dr Rohit sen",
    college: "Dolphin pg College dehradun",
    location: null,
  },
  {
    quote: "Thanks for sharing and giving this opportunity",
    name: "Dr Sameera PT",
    college: "Tagore College of physiotherapy",
    location: null,
  },
  {
    quote: "A very good session from you",
    name: "Fowmidha Begum.N",
    college: "Sree Balaji college of Physiotherapy",
    location: null,
  },
  {
    quote: "Well explained and learned a lot new things",
    name: "Harsha Chennupalli",
    college: "SIMS college of physiotherapy",
    location: null,
  },
  {
    quote: "Previous webinar I attend that seriously awesome, voice is clear, not any internet issue and also teach fully English in a slowly manner but in this webinar he teach little bit Hindi I am not comfortable for that language and also admin has some network issues… then he teach little bit fast also ..",
    name: "Ashiba",
    college: "JP group of institutions",
    location: null,
  },
  {
    quote: "Good webinar",
    name: "Tanushree Shende",
    college: "Indutai Gaikwad Patil college of Physiotherapy",
    location: null,
  },
  {
    quote: "Very good webinar and all doubt is clear",
    name: "Dewre Khalid Kausar Ahmad",
    college: "Kpgu ,BPT 3rd yr",
    location: null,
  },
  {
    quote: "It was great and very helpful",
    name: "Pravallika Choulawar",
    college: "Susruta Institute of Physical Medicine and Rehabilitation",
    location: null,
  },
  {
    quote: "It was a really great experience learning Neuro from you , concepts are now crystal clear Thankyou ❤️🫶",
    name: "Prajkta Gondkar",
    college: "Mahalaxmi college of Physiotherapy",
    location: null,
  },
  {
    quote: "GOOD",
    name: "VIKAS GUPTA",
    college: "SAAII COLLEGE OF MEDICAL SCIENCE AND TECHNOLOGY",
    location: null,
  },
  {
    quote: "Good",
    name: "Harkirat kaur",
    college: "SGRD",
    location: null,
  },
  {
    quote: "Sorry I couldn’t join webinar bcz some issues but I know your teaching style,skills and patterns and a really appreciate them ..",
    name: "Aryan Patel",
    college: "Shree M.M shah physiotherapy college",
    location: null,
  },
  {
    quote: "Good",
    name: "Vimith Flarish",
    college: null,
    location: null,
  },
  {
    quote: "Good",
    name: "Dr Kunal kumar",
    college: null,
    location: "Bihar",
  },
  {
    quote: "Osm",
    name: "Snehil Kumar",
    college: null,
    location: "Up",
  },
  {
    quote: "Very informative",
    name: "Sravan. P",
    college: null,
    location: "Kerala",
  },
  {
    quote: "Well explained class it was, Thankyou sir",
    name: "Meivel",
    college: null,
    location: "Tamilnadu",
  },
  {
    quote: "Starting part are not much. Intrested",
    name: "Parvati Bhati",
    college: null,
    location: "Rajasthan",
  },
  {
    quote: "Fantastic explanation! Concept crystal clear!",
    name: "Karri Bhavya",
    college: null,
    location: "Telangana",
  },
  {
    quote: "It was a very detailed webinar. Explained each and every aspect of Parkinson disease.",
    name: "Dr.Arpita Pandey PT",
    college: null,
    location: "Madhya Pradesh",
  },
  {
    quote: "Easy to understand",
    name: "Aviral Upadhyay",
    college: null,
    location: "Uttar Pradesh",
  },
  {
    quote: "Good teaching skill",
    name: "Radha patel",
    college: null,
    location: "Madhya pradesh",
  },
  {
    quote: "It was soo good",
    name: "Aeman botke",
    college: null,
    location: "Maharashtra",
  },
  {
    quote: "Very informative, simple and easy explanation",
    name: "Dr. Shaila Sheikh",
    college: null,
    location: "Rajasthan",
  },
  {
    quote: "Excellent",
    name: "S.VASANTHI",
    college: null,
    location: "Tamilnadu",
  },
  {
    quote: "Good",
    name: "Rakesh singh",
    college: null,
    location: "Uttarakhand",
  },
  {
    quote: "It was very informative and the efforts taken by the speaker was great ..",
    name: "Dakshata Jitendra Patil",
    college: null,
    location: "Maharashtra",
  },
  {
    quote: "Very well explained",
    name: "Yogeshwari Kolhe",
    college: null,
    location: "Madhya Pradesh",
  },
  {
    quote: "Very good section and improve knowledge about Parkinson's disease and management",
    name: "Muhammed Anshad",
    college: null,
    location: "Kerala",
  },
  {
    quote: "It is very effective session",
    name: "RISHI KUMAR",
    college: null,
    location: "Bihar",
  },
  {
    quote: "It was very informative and helpful",
    name: "Ekta Laxmandas Punjabi",
    college: null,
    location: "Maharashtra",
  },
  {
    quote: "Very informative and precise presentation of the topic.",
    name: "Aiyesha khatun",
    college: null,
    location: "Odisha",
  },
  {
    quote: "It was great to hear the webinar.",
    name: "Dr. Rakhi Kumari",
    college: null,
    location: "Bihar",
  },
  {
    quote: "Understood the topic very well",
    name: "Safa",
    college: null,
    location: "Maharashtra",
  },
  {
    quote: "The webinar was informative and helpful.",
    name: "Nainshi Singh",
    college: null,
    location: "Assam",
  },
  {
    quote: "it was good",
    name: "Deepika chourey",
    college: null,
    location: "Madhya pradesh",
  },
  {
    quote: "Knowledgeable",
    name: "Salim Akhtar",
    college: null,
    location: "Bihar",
  },
  {
    quote: "Very useful",
    name: "Boutharani Shanmugam",
    college: null,
    location: "Tamil Nadu",
  },
  {
    quote: "Sir thank you so much for providing precious time and wonderful knowledge...",
    name: "Sajal Rajak",
    college: null,
    location: "Madhya pradesh",
  },
  {
    quote: "In Very smoothly way to explained. Thank you so much.",
    name: "Md nashim baitha",
    college: null,
    location: "Bihar",
  },
  {
    quote: "Easy way to understanding the topic",
    name: "Dr. Riyaz Ahmad",
    college: null,
    location: "Bihar",
  },
  {
    quote: "Good explanation",
    name: "Janarthan",
    college: null,
    location: "Tamil Nadu",
  },
  {
    quote: "Good",
    name: "Dr Sumit PT",
    college: null,
    location: "Uttar Pradesh",
  },
  {
    quote: "It was informative",
    name: "Abisoori chandhana",
    college: null,
    location: "Kerala",
  },
  {
    quote: "It's really nice but the time is not enough",
    name: "Nanthitha.A.S",
    college: null,
    location: "Tamilnadu",
  },
  {
    quote: "It was a clear explanation",
    name: "Dhivya J",
    college: null,
    location: "Tamilnadu",
  },
  {
    quote: "Good learning but little bit Faster",
    name: "Sibiraj P",
    college: null,
    location: "Tamil Nadu",
  },
  {
    quote: "GOOD",
    name: "Dr Aditi Surve (PT)",
    college: null,
    location: "Maharashtra",
  },
  {
    quote: "Nice sessions",
    name: "J. Britney",
    college: null,
    location: "Tamil Nadu",
  },
  {
    quote: "Thank you for taking such efforts for all the students. Was very helpful for understanding the topic. Excellent explanation. Thank you so much ✨",
    name: "Shaikh Alfiya Quadeer",
    college: null,
    location: "Maharashtra",
  },
  {
    quote: "Very Informative session",
    name: "Dr. Vishal Kumar Namdev",
    college: null,
    location: "Madhyapradesh",
  },
  {
    quote: "Thankyou for this opportunity,I am a intern student. It usefull for this webinar, both up all its briefly explained.",
    name: "Harish Kumar P",
    college: null,
    location: "Tamilnadu",
  },
  {
    quote: "Very useful and informative session",
    name: "MANIKANDAN R",
    college: null,
    location: "Tamilnadu",
  },
  {
    quote: "It was great",
    name: "Supriya jha",
    college: null,
    location: "Bihar",
  },
  {
    quote: "very good but speaking very fast.. otherwise good 👍",
    name: "suhail alam",
    college: null,
    location: "new delhi",
  },
  {
    quote: "Amazing webinar...well explained the topic ,almost covered this huge topic in a short span of time.thank you very much for conducting. Deepest gratitude 🙏🏻",
    name: "Priyanka Mathur",
    college: null,
    location: "Rajasthan",
  },
  {
    quote: "Excellent",
    name: "Dr. Lalit Mohan Sharma",
    college: null,
    location: "Rajasthan",
  },
  {
    quote: "Gud and it's very useful",
    name: "Anusree",
    college: null,
    location: "Tamilnadu",
  },
  {
    quote: "Good interactive session",
    name: "Dhinagaran V",
    college: null,
    location: "TamilNadu",
  },
  {
    quote: "Overall Very good but make it slowly, if topic is too large make it two parts",
    name: "Manoj Kumar",
    college: null,
    location: "Karnataka",
  },
  {
    quote: "Very helpful for us",
    name: "Dharmik Patel",
    college: null,
    location: "Gujarat",
  },
  {
    quote: "Can talk slowly next time",
    name: "MAE BERMUDEZ DIMLA",
    college: null,
    location: "SINGAPORE",
  },
  {
    quote: "Your explanation was the best, the way you explained the pathophysiology is very amazing and simple. Thank you so much sir for all your efforts.",
    name: "Khan Anam",
    college: null,
    location: "Maharashtra",
  },
  {
    quote: "It was too informative and explanatory!!",
    name: "Kajal Anil Korani",
    college: null,
    location: "Maharashtra",
  },
  {
    quote: "Such an amazing way of presentation...this webinar clear my all doubt and confusion related to Parkinson disease...an amazing experience I had.",
    name: "Dr. Shivani jaimini",
    college: null,
    location: "Rajasthan",
  },
  {
    quote: "It was very informative especially the pathophysiology.Was expecting recent advances in PT management",
    name: "Sakshi more",
    college: null,
    location: "Maharashtra",
  },
  {
    quote: "Good webinar",
    name: "Saurav suman",
    college: null,
    location: "Bihar",
  },
  {
    quote: "Overall webinar is good,also sharing the correct way of assessment and treatment plan.",
    name: "Krutika Vikas Gawad",
    college: null,
    location: "Maharashtra",
  },
  {
    quote: "Excellent",
    name: "Dr Rupesh Thakur",
    college: null,
    location: "Bihar",
  },
  {
    quote: "Excellent 👌 sir",
    name: "Sunny kumar",
    college: null,
    location: "Bihar",
  },
  {
    quote: "It was nice",
    name: "Madhuri Kumari",
    college: null,
    location: "Chennai",
  },
  {
    quote: "The webinar is too good, east to understand about Parkinson's. Thank you sir",
    name: "Jabesh BM",
    college: null,
    location: "Tamilnadu",
  },
  {
    quote: "Best",
    name: "Richa rai",
    college: null,
    location: "Uttar pradesh",
  },
  {
    quote: "Excellent webinar",
    name: "Dr Sumit Rajput",
    college: null,
    location: "New Delhi",
  },
  {
    quote: "Useful for us",
    name: "Sujithra. S",
    college: null,
    location: "Tamilnadu",
  },
  {
    quote: "Thank you for the webinar today. It was a pleasure to attend .it will be",
    name: "Dr kavyanjali",
    college: null,
    location: "Telangana",
  },
  {
    quote: "Good to gain knowledge",
    name: "Saranyadevi. V",
    college: null,
    location: "Tamilnadu",
  },
  {
    quote: "Thank you for the webinar today.It was a pleasure to attend.it will be able to carry the lessons learnt there going forward thank again for your knowledge",
    name: "Dr.kavyanjali",
    college: null,
    location: "Telangana",
  },
  {
    quote: "Thank you for the webinar today.it was a pleasure to attend.it will be able to carry the lessons learnt there going forward thank again for the knowledge",
    name: "Dr.kavyanjali",
    college: null,
    location: "Telangana",
  },
  {
    quote: "Amazing explaination of each and every deatil . It was s very informative session . I am glad I took it. No regrets . Looking forward to join more classes .",
    name: "Insha",
    college: null,
    location: "Uttrakhand",
  },
  {
    quote: "The speaker is good, he delivered information relevant, depth, accurate and new insights",
    name: "MD MARGHOOB NEYAZI",
    college: null,
    location: "Bihar",
  },
  {
    quote: "Very awesome",
    name: "Imran Khan",
    college: null,
    location: "Uttar Pradesh",
  },
  {
    quote: "Awesome",
    name: "Imran Khan",
    college: null,
    location: "Uttar Pradesh",
  },
  {
    quote: "Interested",
    name: "Md.Saif",
    college: null,
    location: "Bihar",
  },
  {
    quote: "Super",
    name: "GOKUL S",
    college: null,
    location: "Tamilnadu",
  },
  {
    quote: "Good",
    name: "Dr Rashmi parmar",
    college: null,
    location: "Gujrat",
  },
  {
    quote: "Great explanation 👌",
    name: "Shifa khan",
    college: null,
    location: "Madhya pradesh",
  },
  {
    quote: "V good",
    name: "Ankita Udeniya",
    college: null,
    location: "Bhopal",
  },
  {
    quote: "Good",
    name: "Kinjal shah",
    college: null,
    location: "Gujarat",
  },
  {
    quote: "It's awesome and it's explain in very simple way",
    name: "Syeda Sabha Begum Syed Nisar",
    college: null,
    location: "Maharashtra",
  },
  {
    quote: "It was really helpful learned a lot",
    name: "Natasha saxena",
    college: null,
    location: "Madhya Pradesh",
  },
  {
    quote: "Good 👍",
    name: "Jyoti",
    college: null,
    location: "Haryana",
  },
  {
    quote: "Its should be continued very informative",
    name: "Sahil haider",
    college: null,
    location: "Bihar",
  },
  {
    quote: "Clear concept",
    name: "Arati Vijay Jadhav",
    college: null,
    location: "Maharashtra",
  },
  {
    quote: "All clear concept",
    name: "Arati Vijay Jadhav",
    college: null,
    location: "Maharashtra",
  },
  {
    quote: "Experienced a good lecture with detailed discussion especially on the pathophysiology and assessment part have catch my attention. Thank you for adding up some more knowledge in my learning journey would love to attend lecture like this in future.",
    name: "Kishan Vaishnav",
    college: null,
    location: "Uttarakhand",
  },
  {
    quote: "The webinar was very informative",
    name: "Sakina Ujjainwala",
    college: null,
    location: "Madhya Pradesh",
  },
  {
    quote: "Good...perfectly understand about parkinson disease😊",
    name: "Asima abul kaseem",
    college: null,
    location: "Tamil nadu",
  },
  {
    quote: "Amazing",
    name: "Punitha",
    college: null,
    location: "Tamilnadu",
  },
  {
    quote: "Nice",
    name: "Akash Gupta",
    college: null,
    location: "UP",
  },
  {
    quote: "Presentation was very good. Explained very well touching each and every point.",
    name: "Satyabrata Mohanty",
    college: null,
    location: "Odisha",
  },
  {
    quote: "👍 nice",
    name: "Nick verma",
    college: null,
    location: "Rajasthan",
  },
  {
    quote: "The webinar is good.",
    name: "Ansari shumaila sadaf tajammul husain",
    college: null,
    location: "India",
  },
  {
    quote: "Knowlegdable",
    name: "Prajjwal Singh",
    college: null,
    location: "Uttar Pradesh",
  },
  {
    quote: "Recent advances were expected",
    name: "Ishwari saindane",
    college: null,
    location: "Maharashtra",
  },
]
