const WEBP_RE = /\.webp(\?|#|$)/i
const SVG_RE = /\.svg(\?|#|$)/i
const HTTP_RE = /^https?:\/\//i
const LOCAL_RASTER_RE = /\.(png|jpe?g|gif|bmp|tif{1,2})(\?|#|$)/i

/**
 * Rewrite any image source to a WebP URL.
 *
 * - data: URIs and SVG stay untouched (no raster wrapper needed for vector art).
 * - Already-WebP sources pass through unchanged.
 * - Remote raster images are routed through the on-demand converter at
 *   /api/images, which re-encodes them as WebP regardless of the stored format.
 * - Same-origin raster paths are resolved to the pre-converted `.webp` build
 *   artifact generated by scripts/convert-images.mjs.
 */
export function webpSrc(src: string | null | undefined): string {
  const value = src ?? ""
  if (!value || value.startsWith("data:")) return value
  if (WEBP_RE.test(value) || SVG_RE.test(value)) return value
  if (HTTP_RE.test(value)) {
    return `/api/images?src=${encodeURIComponent(value)}`
  }
  return value.replace(LOCAL_RASTER_RE, ".webp$2")
}