"use client";

const institutions = [
  "Saveetha College of Physiotherapy",
  "Royal Global University",
  "NIMS University Jaipur",
  "R V College of Physiotherapy",
  "LNCT University",
  "SGT University",
  "DPMC",
  "Aadhunik Institute of Paramedical Science",
  "SAIMS",
  "Shri Guru Ram Rai College of Paramedical Sciences",
  "SIMATS",
  "PUPC",
  "TNMC and BYL Nair Hospital",
  "SGRR University",
  "Perspolis",
  "MGM College of Physiotherapy Navi Mumbai",
  "NIMS University",
  "Santosh Medical College",
  "Cm Patel College of Physiotherapy",
  "Index Medical College",
  "Nanjappa Institute of Physiotherapy Shivamogga",
  "NIMS College of Physiotherapy",
  "Yenepoya Physiotherapy College",
  "Kinesis Pain Speciality Centre",
  "MGM Institute of Physiotherapy",
  "KMC Mangalore",
  "MMRTI",
  "Venus College of Medical Science",
  "SGPGI",
  "KLR College of Physiotherapy",
  "Christian Medical College",
  "Terna Physiotherapy College",
  "Yenepoya",
  "Shree M.M Shah Physiotherapy College Mahemdavad",
  "Santosh College of Physiotherapy",
  "Parul University",
  "Department of Physiotherapy Magadh University Bodhgaya",
  "Krishnaguru Adhyatmik Vishvavidyalaya",
  "BHPI",
  "Government Physiotherapy College Raipur",
  "RNTU",
  "LN Medical College",
  "National Paramedical College Agra",
  "Integral University",
  "BG Patel College of Physiotherapy",
  "Maa Chandrika",
  "Uka Tarsadia University",
  "GU",
  "Indian Spinal Injuries Centre",
  "IIMT University Meerut",
  "NIMS College of Physiotherapy and Occupational Therapy",
  "NIS",
  "VSPM'S College of Physiotherapy",
  "Aks University Satna",
  "Shrimad Rajchandra College of Physiotherapy",
  "SBS University",
  "Jamia Hamdard",
  "MGR University",
  "Manipal University",
  "Smt. Radhika Tai Padav College of Physiotherapy",
  "Acharya N R Institute of Physiotherapy",
  "Galgotias University",
  "Sharda University",
  "Jamia Hamdard University",
  "Assam Down Town University",
  "Rk University",
  "Kaduna State University",
  "Allied Health Sciences",
  "The Assam Kaziranga University",
  "JKKM MRF College of Physiotherapy",
  "Mother Teresa Post Graduate and Research Institute of Health Sciences",
  "BB",
  "Manav Rachna University",
  "Mahatma Jyoti Rao Phoole University",
  "Rosy Royal College",
  "Sanskriti University",
  "Doon Medical College",
  "Tirumala College",
  "Sri Devraj Urs Medical College",
  "Mahatma Gandhi Physiotherapy College",
  "Sumandeep Vidyapeeth",
  "KEM",
  "Kanav Rachna International Institute of Research and Studies",
  "BMU",
  "Starex University Gurgaon",
  "GSL College of Physiotherapy & Rehabilitation",
  "JG College of Physiotherapy",
  "Aadhunik Institute of Education and Research",
  "Rajarajeshwari Medical College",
  "SCBS",
  "Rajarajeswari College of Physiotherapy",
  "GCUF",
  "NSCB Medical College Hospital Jabalpur",
  "Rajeev Gandhi College",
  "DIBNS",
  "Shri Guru Ram Rai",
  "MGM School of Physiotherapy",
  "Govt Physiotherapy College",
  "Govt Physiotherapy College Jodhpur",
  "Dayanand Sagar University",
  "Kamalam Viswanathan College of Physiotherapy",
  "Institute of Health Sciences",
  "Kugler Physiotherapy College",
  "Institute of Medical Sciences BHU Varanasi",
  "Amar Jyoti Institute of Physiotherapy",
  "Alvas College of Physiotherapy",
  "University of Management and Technology",
  "KLE Institute of Physiotherapy Belgavi",
  "TMV's Indutai Tilak College of Physiotherapy",
  "SCPM College of Nursing and Paramedical",
  "Riphah International University",
  "Adhunik Institute",
  "IIHER",
  "Maharishi Markandeswar Institute of Physiotherapy and Rehabilitation",
  "Adhunik Institute of Medical College Gaziabad",
  "Sumandeep Vidyapeeth Vadodara Gujarat",
  "Nanjappa Institute of Physiotherapy Shimoga",
  "CIHS Thalassery",
  "School of Physiotherapy",
  "Abhinav Bindra Sports Medicine and Research Institution",
  "Dr Neha",
  "King George Medical University Lucknow",
  "SRM College of Physiotherapy",
  "Krupanidhi College of Physiotherapy",
  "Nilachala Institute of Medical Sciences",
  "Durgabai Deshmukh Hospital Hyderabad",
  "Sam Higginbottom University of Agriculture Technology and Sciences",
  "NIPED",
  "Satish Goswami College of Physiotherapy",
  "Christian College Of Physiotherapy",
  "Neelachal Institute of Medical Sciences",
  "Doon Para Medical",
  "Santhosh College of Physiotherapy",
  "SCP College",
  "MMRTI Para Medical",
  "University of Health and Sciences",
  "Adhunik Institute and Research",
  "Sri Sai College of Physiotherapy",
  "Ahmedabad Institute of Medical Sciences",
  "Sai Saburi Health Science College",
  "SCPM College of Nursing and Paramedical Sciences Gonda",
  "Chitkara University",
  "Ambedkar Institute",
  "St. Soldier Group of Institutions",
  "Chakradhara Institute Of Rehabilitation Sciences",
  "Kasturi College of Physiotherapy",
  "Chakradhar Institute of Rehabilitation Sciences BBSR",
  "PIMS",
  "KIPT",
  "NIEPID",
  "SGCP",
  "Chakradhar Institute of Rehabilitation Sciences Bhubaneswar",
  "Chandigarh University",
  "Sir Dr. M S Gosavi College Of Physiotherapy",
  "Dr Br Ambedkar Medical College Hospital",
  "Ahmedabad Physiotherapy College",
  "Devbhoomi Uttarakhand University",
  "Thanthai Roever College of Physiotherapy",
  "Vaagdevi College of Physiotherapy",
  "GSL Medical College",
  "Government Medical College",
  "Adhunik Institute End Research",
  "GMC",
  "Venus Institute of Physiotherapy",
  "Shri Guru Ram Rai College of Paramedical Sciences",
  "USKT",
  "Swami Rama Himalayan University",
  "College of Physiotherapy",
  "PDDUNIPD",
  "People's College of Paramedical Sciences and Research Center",
  "Mannai Narayanasamy College Of Physiotherapy Thanjavur",
  "AIMS",
  "Integral University",
  "IPS Meerut",
  "Swami Rama Himalayan University Dehradun",
  "Sai Institute of Health Sciences",
  "Smt Radhikatai Pandav College of PT",
  "K. S. Memorial College of Physiotherapy",
  "FEU NRMF",
  "Universidad de Sta. Isabel",
  "Bright Hill Evergreen Company",
  "SCP College",
  "De La Salle Medical and Health Sciences Institute",
  "RRCP",
  "KMPDC",
  "Harsha Institute of Physiotherapy College Nelmangla Bangalore",
  "Upums",
  "University Of Medical Technology",
  "IAMR",
  "Malabar Medical College",
  "Narayana Institute",
  "Shadan College of Physiotherapy",
  "SVIMS",
  "Olivarez College Manila",
  "BSPT Our Lady of Fatime",
  "OLFU QC",
  "UST",
  "Shri Indra Ganesan Institute of Medical Science College of Physiotherapy",
  "Oyster College of Physiotherapy Aurangabad",
  "Aks University Satna",
  "SPB Physiotherapy College",
  "Glasgow Caledonian University",
  "Shri Kk Sheth Physiotherapy College",
  "Motiwala College of Physiotherapy Nashik",
  "Rkdf College Bhopal",
  "Sai Institute of Paramedical and Allied Sciences",
  "Bhausaheb Mulak",
  "NIEPMD",
  "K J Pandya College of Physiotherapy",
  "Government Physiotherapy College Jamnagar",
  "Emilio Aguinaldo College Manila",
  "Itm College",
  "Smt. Kashibai Navale College of Physiotherapy",
  "Upums Saifai Etawah",
  "OCPT",
  "Gopal Narayan Singh University",
  "Royal College of Physiotherapy",
  "Gurugram University Haryana",
  "Bhagwant University Ajmer",
  "Teerthanker Mahaveer University",
  "Indian Institute of Health Education and Research",
  "Gurudeo Paramedical College",
  "Peerless College of Physiotherapy",
  "Manav Rachna International Institute of Research and Studies",
  "Indian Institute Of Health and Education Research",
  "JM Institute of Paramedical",
  "JKK Muniraj College of Physiotherapy and Medical Research Foundation",
  "Pinpms",
  "SRK University",
  "Patna Institute Nursing and Paramedical Sciences",
  "People's University",
  "Cherraan's College of Physiotherapy Coimbatore",
  "U.N. Mehta Institute of Research Centre",
  "Gyansarovar Vidyapeeth College Patna",
  "JKKMMRF College of Physiotherapy",
  "Jkkmmrf College of Physiotherapy",
  "JKKMMRF  College of Physiotherapy",
  "JKKMRF Collage of Physiotherapy",
  "CSJMU Kanpur",
  "Madhya Pradesh Medical Science College",
  "Swasthya Kalyan College of Physiotherapy",
  "Swasthya Kalyan College of Physiotherapy Sitapura Jaipur",
  "Ananya College of Physiotherapy",
  "Swami Vivekanand Para Medical College Simultala Jamui",
  "Apex Institute of Physiotherapy",
  "Oyster College Of Physiotherapy",
  "GJUS&T",
  "GJU Hisar",
  "GPC Patna",
  "GPC",
  "Gurudeo Paramedical College Patna",
  "KINPMS Samastipur",
  "Adhunik Institute of Medical Science",
  "Index Medical College",
  "MGM",
  "Chaudhary Charan Singh University",
  "Pacific College of Physiotherapy",
  "Ahmedabad Physiotherapy College",
  "Nişantaşı Üniversitesi",
  "GMC Nagpur",
  "Vaagdevi College of Physiotherapy",
  "Era University",
  "Health On Us Rehabilitation",
  "Apollo Institute Of Physiotherapy Ahemdabad",
  "Bhagwant University",
  "IMS BHU",
  "Combined Institute of Medical College Dehradun",
  "Amity University",
  "Srinivas University Institute of Physiotherapy Mangalore",
  "HNB Garhwal University",
  "Royal College",
  "Sam Global University",
  "PDUNIPPD",
  "Dr B R Ambedkar Medical College Hospital",
  "Jaipur Physiotherapy College",
  "KMCH College of Physiotherapy",
  "Amaltas Institute of Medical Science",
  "Aryabhatta Knowledge University",
  "Mother Teresa College of Physiotherapy",
  "Sarvajanik College of Physiotherapy",
  "Amaltas Institute of Medical Sciences",
  "Smt.Radhikatai Pandav College of Physiotherapy Nagpur",
  "MUHS",
  "Roever College of Physiotherapy",
  "Ambedkar Institute of Higher Education",
  "Shri B M Patil Medical College BLDEDU",
  "Faculty of Paramedical Science Bareilly",
  "Krishna Institute of Nursing and Paramedical Sciences",
  "Karnataka College of Managements",
  "Scpm Medical College Gonda",
  "Department of Physiotherapy",
  "PPG College of Physiotherapy",
  "RNTU Bhopal",
  "KRISHNA INSTITUTE OF NURSING AND PARAMEDICAL SCIENCES",
  "SRHU",
  "Government Medical College Jalaun Orai",
  "Himalayan Institute of Medical Sciences",
  "Sri Channegowda College of Physiotherapy Kolar",
  "Utkal University",
  "SGRRU",
  "PCPT",
  "New",
  "Amar Jyoti Institute of Physiotherapy",
  "CCS University",
  "PGI Rohtak",
  "Karchi University",
  "IIMT University",
  "Iimt University",
  "Sri Devaraj Urs Medical College",
  "Institute of Applied Medicines & Research Ghaziabad",
  "Ayushman",
  "GMC Jalaun",
  "SBV Mgmcri",
  "MGMCRI School of Physiotherapy Sri Balaji Vidyapeeth",
  "Sri Balaji Vidyapeeth",
  "Abhinav Bindra Sports Medicine Research and Institute of Management",
  "GSL Medical College of Physiotherapy",
  "Karavali College of Physiotherapy",
  "School of Physiotherapy Sri Balaji Vidyapeeth",
  "Dr.Ulhas Patil College of Physiotherapy",
  "INDIAN INSTITUTE OF HEALTH EDUCATION AND RESEARCH",
  "RUHS Jaipur",
  "NSCB Medical College Hospital Jabalpur Madhya Pradesh",
  "Mgr University Affiliated Colleges",
  "Mulago School of Physiotherapy Uganda",
  "Shanthi Ram Hospital",
  "SRM",
  "GH",
  "Akash Institute of Physiotherapy",
  "GJUST",
  "Shri Indra Ganesan College of Physiotherapy",
  "Gurugram University",
  "Mgr University",
  "Kanachur College of Physiotherapy",
  "APCOPT",
  "Vishakha",
  "KIMS College of Physiotherapy",
  "NIMS College of PT/OT",
  "K.G College of Physiotherapy",
  "RMMC&H",
  "RUGHS",
  "KAMALAM VISWANATHAN COLLEGE OF PHYSIOTHERAPY",
  "KMXH COLLEGE OF PHYSIOTHERAPY",
  "Madha College of Physiotherapy",
  "Choithram College",
  "Adhiparasakthi College of Physiotherapy",
  "NHS",
  "Spine Centre",
  "Dadabhoy Institute of Higher Education",
  "CIMS Clg",
  "BIMR",
  "GMC Orai",
  "Banarsidas Chandiwala Institute of Physiotherapy",
  "Shree Venkateshwar College of Paramedical Science",
  "SCPM College Gonda",
  "Rabindranath Tagore University",
  "Assam Down Town University",
  "YBN University Ranchi",
  "Aryabhatta Knowledge University",
  "North East Christian University",
  "IPGME&R SSKM Hospital Kolkata",
  "RDGMC College",
  "People's College Bhopal",
  "SAIMS Indore",
  "BMU",
  "BIMTS",
  "Ambedkar Medical College Hospital",
  "VSPM College of Physiotherapy",
  "Kasturi College of Physiotherapy",
  "Bundelkhand University",
  "MGM Institute of Physiotherapy Chh Sambhajinagar",
  "ITS IHAS",
  "Banarsi Chandiwala Delhi",
  "AKU Patna",
  "Apollo College of Physiotherapy Anjora Durg",
  "Apollo College of Physiotherapy Durg",
  "Mewar University",
  "Dy Patil",
  "BSS",
  "Harsha Institution of Physiotherapy",
  "Kaziranga University",
  "Pacific University",
  "Venus Institute of Physiotherapy",
];

export function TrustedBySection() {
  const duplicatedInstitutions = [...institutions, ...institutions];

  return (
    <section className="w-full bg-white py-12 md:py-24 overflow-hidden">
      <div className="max-w-7xl mx-auto px-4 md:px-6">
        <p className="text-center text-gray-600 text-sm md:text-base font-medium mb-10 md:mb-16">
          Students from these institutions learn with us
        </p>

        <div className="relative">
          <div className="flex animate-scroll">
            {duplicatedInstitutions.map((institution, index) => (
              <div
                key={index}
                className="flex-shrink-0 mx-4 md:mx-6"
              >
                <p className="text-xs md:text-sm text-gray-600 whitespace-nowrap font-medium px-4 py-2 rounded-lg bg-gray-100">
                  {institution}
                </p>
              </div>
            ))}
          </div>
        </div>
      </div>

      <style jsx>{`
        @keyframes scroll {
          0% {
            transform: translateX(0);
          }
          100% {
            transform: translateX(-50%);
          }
        }
        .animate-scroll {
          animation: scroll 30s linear infinite;
        }
        .animate-scroll:hover {
          animation-play-state: paused;
        }
      `}</style>
    </section>
  );
}
